server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/empdb
    username: root
    password: root


##起一个别名
mybatis:
  type-aliases-package: com.myybatis.pojo
  mapper-locations: classpath:mapper/*.xml

##引入mapper映射文件

